// Package clockfuse ports the snapshot arithmetic; the analyzer stays in the consumer.
package clockfuse

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

type Tools interface {
	Clockfuse(context.Context, string) ([]byte, error)
	ShortHead(context.Context, string) ([]byte, error)
}

type Result struct {
	SchemaVersion   string   `json:"schema_version"`
	Subject         string   `json:"subject"`
	Outcome         string   `json:"outcome"`
	Reason          string   `json:"reason"`
	Findings        []string `json:"findings"`
	SnapshotWritten bool     `json:"snapshot_written"`
	ExitCode        int      `json:"exit_code"`
}

var finding = regexp.MustCompilePOSIX("^[[:space:]]*([^:]+):[0-9]+: ([A-Za-z0-9_.]+)\\{?\\.*\\}?[^`]*`([A-Za-z0-9_]+)`.*")

// Normalize preserves grep/sed/sort/uniq/awk order, including sed's unchanged
// unmatched lines and awk's first whitespace-delimited field after the count.
func Normalize(raw string) []string {
	counts := map[string]int{}
	for _, line := range strings.Split(raw, "\n") {
		if !strings.Contains(line, "omits `") {
			continue
		}
		if m := finding.FindStringSubmatch(line); m != nil {
			line = m[1] + "|" + m[2] + "|" + m[3]
		}
		counts[line]++
	}
	keys := make([]string, 0, len(counts))
	for line := range counts {
		keys = append(keys, line)
	}
	sort.Strings(keys)
	lines := make([]string, 0, len(keys))
	for _, key := range keys {
		fields := strings.Fields(key)
		word := ""
		if len(fields) > 0 {
			word = fields[0]
		}
		lines = append(lines, fmt.Sprintf("%d|%s", counts[key], word))
	}
	return lines
}

func Compare(lines []string, snapshot, root string) (string, int) {
	var out strings.Builder
	newClasses := 0
	for _, line := range lines {
		parts := strings.SplitN(line, "|", 4)
		for len(parts) < 4 {
			parts = append(parts, "")
		}
		count, _ := strconv.Atoi(parts[0])
		key := strings.Join(parts[1:], "|")
		have := ""
		for _, saved := range strings.Split(snapshot, "\n") {
			fields := strings.Split(saved, "|")
			for len(fields) < 4 {
				fields = append(fields, "")
			}
			if strings.Join(fields[1:4], "|") == key {
				if have != "" {
					have += "\n"
				}
				have += fields[0]
			}
		}
		if have == "" {
			have = "0"
		}
		n, err := strconv.Atoi(have)
		if err != nil {
			return "CANNOT-EVALUATE: malformed snapshot count for " + key, 2
		}
		if count > n {
			fmt.Fprintf(&out, "  NEW FINDING  %s — %d now vs %s in snapshot\n", key, count, have)
			newClasses++
		}
	}
	if newClasses == 0 {
		return "clockfuse-gate: no findings above snapshot.", 0
	}
	fmt.Fprintf(&out, "clockfuse-gate: %d NEW finding-class(es) above snapshot. Either inject the\nclock seam in the new test, or — if it is genuinely benign — re-run\n  lictor clockfuse --repo %s --snapshot\nand say why in the commit. Do NOT edit the snapshot by hand.", newClasses, root)
	return out.String(), 1
}

func Run(ctx context.Context, root string, snapshot bool, tools Tools) Result {
	r := Result{SchemaVersion: "lictor.clockfuse.v1", Subject: filepath.Base(root), Outcome: "cannot_evaluate", ExitCode: 2, Findings: []string{}}
	refuse := func(reason string) Result { r.Reason = "CANNOT-EVALUATE: " + reason; return r }
	st, err := os.Stat(filepath.Join(root, "tools", "clockfuse"))
	if err != nil || !st.IsDir() {
		return refuse(root + " has no tools/clockfuse")
	}
	var saved []byte
	if !snapshot {
		f, err := os.Open(filepath.Join(root, ".clockfuse-snapshot"))
		if err != nil {
			return refuse(root + "/.clockfuse-snapshot missing — run --snapshot first.")
		}
		st, err := f.Stat()
		if err != nil || !st.Mode().IsRegular() {
			f.Close()
			return refuse("snapshot is not a regular readable file")
		}
		saved, err = io.ReadAll(io.LimitReader(f, 8<<20+1))
		f.Close()
		if err != nil || len(saved) > 8<<20 {
			return refuse("snapshot unreadable or exceeds 8 MiB")
		}
	}
	raw, err := tools.Clockfuse(ctx, root)
	var exit *exec.ExitError
	if err != nil && !errors.As(err, &exit) {
		return refuse("go clockfuse could not run: " + err.Error())
	}
	r.Findings = Normalize(string(raw))
	if snapshot {
		head, err := tools.ShortHead(ctx, root)
		if err != nil {
			head = []byte("untracked")
		}
		body := "# clockfuse findings snapshot — generated by lictor clockfuse --snapshot\n# " + strings.TrimSpace(string(head)) + "\n# Format: count|file|type|field. Line numbers deliberately absent.\n# REGENERATE with the command above; never edit by hand.\n"
		if len(r.Findings) > 0 {
			body += strings.Join(r.Findings, "\n") + "\n"
		}
		dir, err := os.OpenRoot(root)
		if err != nil {
			return refuse(err.Error())
		}
		defer dir.Close()
		st, err := dir.Lstat(".clockfuse-snapshot")
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return refuse(err.Error())
		}
		if err == nil && !st.Mode().IsRegular() {
			return refuse("snapshot destination is not a regular file")
		}
		if err := dir.WriteFile(".clockfuse-snapshot", []byte(body), 0644); err != nil {
			return refuse("write snapshot: " + err.Error())
		}
		r.SnapshotWritten = true
		r.ExitCode = 0
		r.Reason = fmt.Sprintf("clockfuse-gate: snapshot written — %d finding-class(es) at %s/.clockfuse-snapshot", len(r.Findings), root)
	} else {
		r.Reason, r.ExitCode = Compare(r.Findings, string(saved), root)
	}
	r.Outcome = []string{"pass", "fail", "cannot_evaluate"}[r.ExitCode]
	return r
}
