package clockfuse

import (
	"context"
	"errors"
	"flag"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

var sourceScript = flag.String("clockfuse-source-script", "", "optional source-script conformance proof")

const baseline = "# header\n2|internal/service/a_test.go|FooConfig|Now\n1|internal/setup/b_test.go|Deps|Now\n"

func a(line string) string {
	return "  internal/service/a_test.go:" + line + ": FooConfig{...} omits `Now` -> falls back to the wall clock\n"
}
func b(line string) string {
	return "  internal/setup/b_test.go:" + line + ": Deps{...} omits `Now` -> falls back to the wall clock\n"
}

// RULE: CLOCKFUSE-SNAPSHOT-1
func TestRule_CLOCKFUSE_SNAPSHOT_1(t *testing.T) {
	for _, tc := range []struct {
		name, raw string
		code      int
	}{
		{"identical", a("10") + a("99") + b("7"), 0},
		{"line-churn", a("500") + a("501") + b("999"), 0},
		{"fewer", b("7"), 0},
		{"new-class", a("10") + a("99") + b("7") + "  internal/new/c_test.go:5: BarOptions{...} omits `Clock` -> falls back to the wall clock\n", 1},
		{"count-rise", a("10") + a("99") + a("120") + b("7"), 1},
	} {
		t.Run(tc.name, func(t *testing.T) {
			lines := Normalize(tc.raw)
			out, code := Compare(lines, baseline, "<repo>")
			if code != tc.code {
				t.Fatalf("want %d got %d: %s; normalized=%q", tc.code, code, out, lines)
			}
			if code == 1 && !strings.Contains(out, "  NEW FINDING  ") {
				t.Fatalf("failure lacks new class: %s", out)
			}
			t.Logf("port exit=%d %s", code, out)
			if *sourceScript != "" {
				snap := filepath.Join(t.TempDir(), "snapshot")
				if err := os.WriteFile(snap, []byte(baseline), 0600); err != nil {
					t.Fatal(err)
				}
				cmd := exec.CommandContext(t.Context(), "/bin/bash", *sourceScript, "--check-stdin", snap)
				cmd.Stdin = strings.NewReader(tc.raw)
				cmd.Env = append(os.Environ(), "LC_ALL=C")
				source, err := cmd.CombinedOutput()
				sourceCode := 0
				if err != nil {
					var exit *exec.ExitError
					if !errors.As(err, &exit) {
						t.Fatal(err)
					}
					sourceCode = exit.ExitCode()
				}
				expected := strings.ReplaceAll(strings.TrimSuffix(string(source), "\n"), "wiki/tools/clockfuse-gate.sh --snapshot <repo>", "lictor clockfuse --repo <repo> --snapshot")
				if sourceCode != code || expected != out {
					t.Fatalf("source/port differ: source=(%d,%q), port=(%d,%q)", sourceCode, source, code, out)
				}
				t.Logf("source exit=%d %s", sourceCode, strings.TrimSpace(string(source)))
			}
		})
	}
}

func TestNormalizerPreservesFilterAndUnmatchedLines(t *testing.T) {
	raw := "ignore diagnostic\n" + a("20") + a("21") + "odd omits `Now`\n"
	want := "2|internal/service/a_test.go|FooConfig|Now\n1|odd"
	if got := strings.Join(Normalize(raw), "\n"); got != want {
		t.Fatalf("normalization: got %q want %q", got, want)
	}
}

type fixtureTools struct {
	raw string
	err error
}

func (f fixtureTools) Clockfuse(context.Context, string) ([]byte, error) { return []byte(f.raw), f.err }
func (fixtureTools) ShortHead(context.Context, string) ([]byte, error) {
	return []byte("1234567\n"), nil
}

func TestRunReadOnlySnapshotAndRefusals(t *testing.T) {
	root := t.TempDir()
	tools := fixtureTools{raw: a("10") + a("99") + b("7"), err: &exec.ExitError{}}
	if r := Run(t.Context(), root, false, tools); r.ExitCode != 2 || !strings.Contains(r.Reason, "no tools/clockfuse") {
		t.Fatalf("missing analyzer: %+v", r)
	}
	if err := os.MkdirAll(filepath.Join(root, "tools/clockfuse"), 0700); err != nil {
		t.Fatal(err)
	}
	if r := Run(t.Context(), root, false, tools); r.ExitCode != 2 || !strings.Contains(r.Reason, "snapshot missing") {
		t.Fatalf("missing snapshot: %+v", r)
	}
	r := Run(t.Context(), root, true, tools)
	if r.ExitCode != 0 || !r.SnapshotWritten {
		t.Fatalf("snapshot: %+v", r)
	}
	path := filepath.Join(root, ".clockfuse-snapshot")
	before, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "# clockfuse findings snapshot — generated by lictor clockfuse --snapshot\n# 1234567\n# Format: count|file|type|field. Line numbers deliberately absent.\n# REGENERATE with the command above; never edit by hand.\n" + strings.TrimPrefix(baseline, "# header\n")
	if string(before) != want {
		t.Fatalf("snapshot bytes: %q", before)
	}
	r = Run(t.Context(), root, false, tools)
	after, err := os.ReadFile(path)
	if err != nil || string(after) != string(before) || r.ExitCode != 0 || r.SnapshotWritten {
		t.Fatalf("read-only check: %+v %v", r, err)
	}
	if r := Run(t.Context(), root, false, fixtureTools{err: exec.ErrNotFound}); r.ExitCode != 2 || !strings.Contains(r.Reason, "could not run") {
		t.Fatalf("missing go: %+v", r)
	}
	if r := Run(t.Context(), root, false, fixtureTools{err: context.Canceled}); r.ExitCode != 2 {
		t.Fatalf("cancellation: %+v", r)
	}
	if err := os.Remove(path); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink("other", path); err != nil {
		t.Fatal(err)
	}
	if r := Run(t.Context(), root, true, tools); r.ExitCode != 2 {
		t.Fatalf("symlink write: %+v", r)
	}
}
